name: ${project.artifactId}
version: '${project.version}'
main: com.rappytv.labyutils.bukkit.LabyUtilsBukkit
api-version: '1.13'
authors: [ RappyTV ]
description: ${project.description}
website: ${project.url}
softdepend:
  - Vault
  - PlaceholderAPI

permissions:
  labyutils.bypass.*:
    default: op
    description: Ignores any recommended, required, or disallowed addons
  labyutils.info:
    default: op
    description: Lets the player use /labyinfo
  labyutils.info.subtitle:
    default: op
    description: Lets the player see a player's server subtitle with /labyinfo
  labyutils.info.economy:
    default: op
    description: Lets the player see a player's economy balances with /labyinfo
  labyutils.info.version:
    default: op
    description: Lets the player see a player's LabyMod version with /labyinfo
  labyutils.info.region:
    default: op
    description: Lets the player see a player's region with /labyinfo
  labyutils.permissions.*:
    default: op
    description: Gives the player all configured LabyMod permissions
  labyutils.reload:
    default: op
    description: Lets the player reload the config with /labyutils

commands:
  labyinfo:
    description: Shows LabyMod specific info about a player
    permission: labyutils.info
  labyutils:
    description: Reloads the plugin config
    permission: labyutils.reload
